# 11ty build
[build]
  publish = "_site"
  command = "eleventy"

# Security policy
[[headers]]
for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Cross-Origin-Resource-Policy = "same-site"
  Cross-Origin-Embedder-Policy = "same-origin"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "upgrade-insecure-requests"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# page routes
[[redirects]]
from = "/blog"
to = "/journals"
status = 301
force = true

[[redirects]]
from = "/posts"
to = "/archives"
status = 301
force = true

[[redirects]]
from = "/about"
to = "/pages/about"
status = 301
force = true

[[redirects]]
from = "/contact"
to = "/pages/elect"
status = 301
force = true

[[redirects]]
from = "/news"
to = "/pages/news"
status = 301
force = true

[[redirects]]
from = "/feed"
to = "/feed.xml"
status = 301
force = true

[[redirects]]
from = "/rss"
to = "/rss.xml"
status = 301
force = true

[[redirects]]
from = "/sitemap"
to = "/sitemap.xml"
status = 301
force = true

[[redirects]]
from = "/help"
to = "/assistant"
status = 301
force = true

[[redirects]]
from = "/logo.png"
to = "/assets/images/kiri-vadivelu.jpg"
status = 301
force = true

# social media 
[[redirects]]
from = "/twitter"
to = "https://twitter.com/kiri_vadivelu"
status = 301
force = true

[[redirects]]
from = "/instagram"
to = "https://instagram.com/kiri_vadivelu"
status = 301
force = true

[[redirects]]
from = "/facebook"
to = "https://facebook.com/kiri.vadivelu"
status = 301
force = true

[[redirects]]
from = "/linkedin"
to = "https://linkedin.com/in/kiri-vadivelu"
status = 301
force = true

[[redirects]]
from = "/github"
to = "https://github.com/kiri-vadivelu"
status = 301
force = true

[[redirects]]
from = "/hashnode"
to = "https://scarborough.hashnode.dev"
status = 301
force = true

[[redirects]]
from = "/substack"
to = "https://scarborough.substack.com"
status = 301
force = true

[[redirects]]
from = "/tealfeed"
to = "https://tealfeed.com/scarborough"
status = 301
force = true

# netlify redirect
[[redirects]]
  from = "https://kiri-vadivelu.netlify.app"
  to = "https://kiri-vadivelu.ca"
  status = 301
  force = true

# web analytics
[[redirects]]
  from = "https://kiri-vadivelu.ca/g/collect"
  to = "https://google-analytics.com/g/collect"
  status = 200
  force = true