# Security header/ Digital Designers 
# Implemented for https://kiri-vadivelu.ca

[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/g/collect"
  to = "https://kiri-vadivelu.ca/g/collect"
  status = 200

[[redirects]]
  from = "https://kiri-vadivelu.netlify.app"
  to = "https://kiri-vadivelu.ca"
  status = 301
  force = true

[[headers]]

  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"

  X-Content-Type-Options = "nosniff"

  Cross-Origin-Resource-Policy = "same-site"

  Cross-Origin-Embedder-Policy = "same-origin"

  Referrer-Policy = "strict-origin-when-cross-origin"

  Content-Security-Policy = "upgrade-insecure-requests"

  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

